export const BRAND = {
  name: 'MC TITOE EVENTS AND DESIGNS',
  shortName: 'MC TITOE',
  subName: 'EVENTS & DESIGNS',
  legalName: 'MC Titoe Events and Designs',
  tagline: 'We Turn Your Vision Into an Unforgettable Event.',
  subTagline: 'From charismatic hosting and concert sound to bespoke decor, lighting, and turnkey event planning, we bring every important detail together.',
  footerTagline: 'Bespoke event production, charismatic hosting, and transformative design in Mombasa & across Kenya.',
  contact: {
    phone: '+254 721 784 682',
    phoneFormatted: '+254 721 784 682',
    phoneRaw: '+254721784682',
    whatsapp: '0782 527 081',
    whatsappFormatted: '+254 782 527 081',
    whatsappRaw: '+254782527081',
    whatsappLink: 'https://wa.me/254782527081',
    helpline: '0758 726 167',
    helplineFormatted: '+254 758 726 167',
    email: 'mctitoeeventsdesigns@gmail.com',
    supportEmail: 'mctitoeeventsdesigns@gmail.com',
    address: 'Bamburi, Mombasa, Kenya',
    city: 'Mombasa',
    hours: '24 Hours (Monday – Saturday)',
  },
  depositPolicy: {
    depositPercentage: 50,
    depositText: '50% deposit upon quote acceptance to lock down the event date',
    balanceText: 'Balance cleared 48 hours before the event',
  },
  cancellationPolicy: [
    { notice: '60+ Days Prior', refund: '100% refund (minus non-refundable deposit / administrative fee)' },
    { notice: '30–59 Days Prior', refund: '50% refund of total fee' },
    { notice: '14–29 Days Prior', refund: '25% refund or full amount applied as credit for a future event' },
    { notice: 'Less than 14 Days', refund: 'No refund issued; 100% of fees forfeited' },
  ],
  pricing: {
    mcStartingRate: 20000,
    mcPricingNote: 'Starting from KSh 20,000 (negotiable)',
    customPricingNote: 'Customized based on client requirements & event scale',
  },
  socials: [
    { label: 'TikTok', handle: 'Tiogs', url: 'https://www.tiktok.com/@Tiogs' },
    { label: 'YouTube', handle: 'Tiogs', url: 'https://www.youtube.com/@Tiogs' },
    { label: 'Facebook', handle: 'Titoe tv', url: 'https://www.facebook.com/Titoetv' },
    { label: 'WhatsApp', handle: '0782 527 081', url: 'https://wa.me/254782527081' },
  ],
};
